# Generated by Django 4.2.11 on 2024-04-24 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='slug',
            field=models.SlugField(allow_unicode=True, auto_created=True, unique=True),
        ),
    ]
